### ISSUE TITLE
Cargo caching is defeated by `cargo:rerun-if-changed=.`

### ISSUE THREAD

**Issue by graydon** [stellar/crate-git-revision#4]
The init function calls `writeln!(w, "cargo:rerun-if-changed=.")?;` which instructs cargo to treat everything under `.` as a timestamp dependency. When this is used in a `build.rs` script unfortunately the script's _output_ in the `target/` dir (built in the same workspace) is considered as one such dependency, so this causes constant cache-misses on cargo.

You can see this if you do a build with `CARGO_LOG=cargo::core::compiler::fingerprint=info cargo check`. For example, when I build `rs-stellar-xdr` that uses this in its build.rs script, I get constant outputs like:

```
...
[2022-11-24T23:53:09Z INFO  cargo::core::compiler::fingerprint] stale: changed "/home/graydon/src/rs-stellar-xdr/."
[2022-11-24T23:53:09Z INFO  cargo::core::compiler::fingerprint]           (vs) "/home/graydon/src/rs-soroban-env/target/debug/build/stellar-xdr-f2aaef79c8132a31/output"
[2022-11-24T23:53:09Z INFO  cargo::core::compiler::fingerprint]                FileTime { seconds: 1669333985, nanos: 561232932 } != FileTime { seconds: 1669333985, nanos: 933228761 }
...
```

This in turn means that rust-analyzer spends tens of seconds rebuilding rs-stellar-xdr and everything that depends on it whenever I save a file.

If I remove this one line and manually set the rerun-if-changed lines to a list of specific files I want to monitor (say the `xdr` directory alone) it works. I'm not sure if that's the best solution, but depending on `.` probably isn't what we want. There doesn't seem to be a way to anti-depend on `target/` which is what we'd probably prefer.

**Comment by leighmcculloch** [comment]
Thanks for identifying this issue. I'll take a look. We actually probably do not need the rerun-if-changed directive at all because the default includes the entire package anyway.
